### ISSUE TITLE
Upkeep for tidyr

### ISSUE THREAD

**Issue by DavisVaughan** [tidyverse/tidyr#1329]
Pre-history

* [x] `usethis::use_readme_rmd()`
* [x] `usethis::use_roxygen_md()`
* [x] `usethis::use_github_links()`
* [x] `usethis::use_pkgdown_github_pages()`
* [x] `usethis::use_tidy_github_labels()`
* [x] `usethis::use_tidy_style()` https://github.com/tidyverse/tidyr/pull/1330
* [x] `usethis::use_tidy_description()`
* [x] `urlchecker::url_check()`

2020

* [x] `usethis::use_package_doc()`
Consider letting usethis manage your `@importFrom` directives here.
`usethis::use_import_from()` is handy for this.
* [x] `usethis::use_testthat(3)` and upgrade to 3e, [testthat 3e vignette](https://testthat.r-lib.org/articles/third-edition.html)
* [x] Align the names of `R/` files and `test/` files for workflow happiness.
`usethis::rename_files()` can be helpful.

2021

* [x] `usethis::use_tidy_dependencies()`
* [x] `usethis::use_tidy_github_actions()` and update artisanal actions to use `setup-r-dependencies`
* [x] Remove check environments section from `cran-comments.md`
* [ ] Bump required R version in DESCRIPTION to 3.4
* [x] Use lifecycle instead of artisanal deprecation messages, as described in [Communicate lifecycle changes in your functions](https://lifecycle.r-lib.org/articles/communicate.html)
* [x] Add RStudio to DESCRIPTION as funder, if appropriate

2022

* [x] `usethis::use_tidy_coc()`
* [x] ~Update errors to rlang 1.0.0~ (Handling in https://github.com/tidyverse/tidyr/issues/1313)
* [x] Update pkgdown site using instructions at <https://tidytemplate.tidyverse.org>
* [x] Re-publish released site using [r-lib/pkgdown#2051](https://github.com/r-lib/pkgdown/pull/2051)
* [x] Ensure pkgdown `development` is `mode: auto` in pkgdown config
* [x] Handle and close any still-open `master` --> `main` issues
* [x] Update README badges, instructions in [r-lib/usethis#1594](https://github.com/r-lib/usethis/issues/1594)

**Comment by DavisVaughan** [comment]
Done in 947f526ad1ca7f22579e4fe9cb53cf26bf9f3d1d...31e83a148b000d01b1cf9265542d78c5b571b9b7
