### ISSUE TITLE
tidyr 1.3.0 revdep tracker

### ISSUE THREAD

**Issue by DavisVaughan** [tidyverse/tidyr#1453]
## Disallow renaming in tidy-selection
- [x] ggpubr: https://github.com/kassambara/ggpubr/issues/536
- [x] metaconfoundr: https://github.com/malcolmbarrett/metaconfoundr/pull/16
- [x] recipes: https://github.com/tidymodels/recipes/pull/1070
- [x] tidypaleo: https://github.com/paleolimbot/tidypaleo/pull/9

## Misc
- [x] faux: https://github.com/debruine/faux/pull/100
- [x] hlaR: https://github.com/tidyverse/tidyr/pull/1454
- [x] mapme.biodiversity: https://github.com/mapme-initiative/mapme.biodiversity/pull/119
- [x] panelr: https://github.com/jacob-long/panelr/pull/53
- [x] wpa: https://github.com/microsoft/wpa/pull/233

## False alarms
- [x] gprofiler2: Looks like false alarm: "Bad request, response code 502"
- [x] openalexR: Pretty sure false alarm. It shows up a lot in other packages too.
